### ISSUE TITLE
什么时候加下载设置功能？我想直接保存，不需要点多图。

### ISSUE THREAD

**Issue by dsyo2008** [tobiichiamane/pixivfs-uwp#1]
希望加这个功能，我喜欢这个uwp。
PS:搜索貌似不能用？

**Comment by tobiichiamane** [comment]
有打算在瀑布流页面加上右键菜单。
搜索还没做，正在做，目前处于乞丐界面状态。
![image](https://user-images.githubusercontent.com/14824064/58261584-2d09b000-7dab-11e9-9097-682583615214.png)

**Comment by dsyo2008** [comment]
> 
> 
> 有打算在瀑布流页面加上右键菜单。
> 搜索还没做，正在做，目前处于乞丐界面状态。
> ![image](https://user-images.githubusercontent.com/14824064/58261584-2d09b000-7dab-11e9-9097-682583615214.png)

非常感谢，还行！等你完善哈，终于找到你，那商店很久没更新。确实微软不让上架。

**Comment by tobiichiamane** [comment]
> > 有打算在瀑布流页面加上右键菜单。
> > 搜索还没做，正在做，目前处于乞丐界面状态。
> > ![image](https://user-images.githubusercontent.com/14824064/58261584-2d09b000-7dab-11e9-9097-682583615214.png)
> 
> 非常感谢，还行！等你完善哈，终于找到你，那商店很久没更新。确实微软不让上架。

不是说不让上架，只要解释清楚了是可以上架的，问题的关键在于你知道大陆的特殊情况，然后随机某个用户下载了->登录不上去->给1星，这个风评被害受不起啊

**Comment by tobiichiamane** [comment]
搜索可以用了，见tag v0.1.6

**Comment by dsyo2008** [comment]
> 
> 
> 搜索可以用了，见tag v0.1.6

收到了，准备编译哈

**Comment by tobiichiamane** [comment]
> 搜索可以用了，见tag v0.1.6
> 
> 收到了，准备编译哈

你完全可以不必自己编译。每一个Tag都会在Releases页面有自动编译好的包，每一次push都会在https://dev.azure.com/tobiichiamane/pixivfs-uwp/_build?definitionId=1处有自动编译好的包

**Comment by dsyo2008** [comment]
> 
> 
> > 搜索可以用了，见tag v0.1.6
> > 收到了，准备编译哈
> 
> 你完全可以不必自己编译。每一个Tag都会在Releases页面有自动编译好的包，每一次push都会在[https://dev.azure.com/tobiichiamane/pixivfs-uwp/_build?definitionId=1处有自动编译好的包](https://dev.azure.com/tobiichiamane/pixivfs-uwp/_build?definitionId=1%E5%A4%84%E6%9C%89%E8%87%AA%E5%8A%A8%E7%BC%96%E8%AF%91%E5%A5%BD%E7%9A%84%E5%8C%85)

OK，了解！

**Comment by tobiichiamane** [comment]
已经可以快速收藏了，快速下载正在做。见提交 d908b43d1c59ed5c96413c2a3d56d1aedb01d886 ；
另外想咨询一下，从一个用户的角度，如果对于一个多图作品，右键快速下载的话，你是希望仅下载封面图，还是把作品内所有的图打包下载？

**Comment by dsyo2008** [comment]
> 
> 
> 已经可以快速收藏了，快速下载正在做。见提交 [d908b43](https://github.com/tobiichiamane/pixivfs-uwp/commit/d908b43d1c59ed5c96413c2a3d56d1aedb01d886) ；
> 另外想咨询一下，从一个用户的角度，如果对于一个多图作品，右键快速下载的话，你是希望仅下载封面图，还是把作品内所有的图打包下载？

是下载封面图，我习惯！打包的话应该考虑后面吧。

**Comment by tobiichiamane** [comment]
快速收藏和快速下载已经可以使用了，见tag v0.1.7。后退栈马上开始动工，这个issue先关掉了。

**Comment by tobiichiamane** [comment]
后退基本可以用了，等我想到定位到上次浏览位置的方法就完善了。

**Comment by tobiichiamane** [comment]
@all-contributors please add @dsyo2008 for ideas
