### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by easyNullThread** [tobiichiamane/pixivfs-uwp#10]
登录后，加载页面一直未出来，然后几秒钟后闪退
请问有日志么，系统版本18362.267

**Comment by tobiichiamane** [comment]
暂时还没有收集错误日志。您使用了实验性的“直连”功能吗？

**Comment by tobiichiamane** [comment]
问题也许被找到了。但是彻底的修复也许还需要一段时间

**Comment by tobiichiamane** [comment]
也许和 #11 有关。此 issue 暂时关闭。
