### ISSUE TITLE
“解除UWP应用本地回环限制”。请问解除限制之后，想要还原回去，该怎么办？

### ISSUE THREAD

**Issue by windflower57521** [tobiichiamane/pixivfs-uwp#101]
来着商店的应用，解除限制之后，和代理软件冲突。想还原回去，怎么办

**Comment by tobiichiamane** [comment]
如果您使用Fiddler，可以将勾勾去掉再保存即可

**Comment by frg2089** [comment]
CheckNetIsolation loopbackexempt -d -n=软件包名
软件包名参考[解除UWP应用本地回环限制](https://github.com/tobiichiamane/pixivfs-uwp/blob/master/TroubleShoot.md#%E8%A7%A3%E9%99%A4uwp%E5%BA%94%E7%94%A8%E6%9C%AC%E5%9C%B0%E5%9B%9E%E7%8E%AF%E9%99%90%E5%88%B6)
