### ISSUE TITLE
Downloads中莫名出现FOO1-5切无法删除。点击删除按钮则会出现重复FOO1-5

### ISSUE THREAD

**Issue by CrazyDoge666** [tobiichiamane/pixivfs-uwp#108]
**Describe the bug/描述你遇到的问题**Downloads中莫名出现FOO1-5切无法删除。点击删除按钮则会出现重复FOO1-5

**How to [reproduce/复现问题的步骤**点击Downloads与删除](url)

**Additional information/额外信息**
Please paste the information copied from the app below if you experienced a crash.
如果您遭遇了崩溃，请将从应用中复制的信息粘贴在下面。
![QQ截图20200830131020](https://user-images.githubusercontent.com/36259181/91651676-3ad7d600-eac2-11ea-9729-29192273e527.png)
![QQ截图20200830131028](https://user-images.githubusercontent.com/36259181/91651677-3c090300-eac2-11ea-81c7-ccf55bfedeee.png)

**Comment by frg2089** [comment]
这是已知问题 这个下载页面是测试功能 🐟抬升版本的时候忘记取消了
不影响使用 因为当前版本并没有使用下载管理的相关功能

**Comment by tobiichiamane** [comment]
啊，这是个work in progress的东西，我发新版本的时候忘记屏蔽掉了
