### ISSUE TITLE
下载页面出现bug

### ISSUE THREAD

**Issue by HikariXu** [tobiichiamane/pixivfs-uwp#109]
**Describe the bug/描述你遇到的问题**
下载页面出现问题，出现名为Foo1、Foo2的2个下载中的文件，在点击downloaded后再点击downloding后，又出现2个一样名字的下中的文件。具体如下图：
![image](https://user-images.githubusercontent.com/45059926/92584954-e5bc7100-f2c6-11ea-98d8-6491fc6583b6.png)

**How to reproduce/复现问题的步骤**
1. 点击右上角的查看下载按钮
2. 点击downloaded按钮
3. 点击downloading按钮

**Additional information/额外信息**
Please paste the information copied from the app below if you experienced a crash.
如果您遭遇了崩溃，请将从应用中复制的信息粘贴在下面。

**Comment by frg2089** [comment]
#108

**Comment by frg2089** [comment]
下载管理功能未实装 这里的下载管理并没有任何作用

**Comment by HikariXu** [comment]
> 下载管理功能未实装 这里的下载管理并没有任何作用

才发现的这个功能，遇到后看到open的issue里没有就反馈了，忘记了检查关闭的issue了。
