### ISSUE TITLE
希望可以增加18+选项 没有18+没灵魂啊

### ISSUE THREAD

**Issue by 0ran** [tobiichiamane/pixivfs-uwp#110]
**Describe the bug/描述你遇到的问题**

**How to reproduce/复现问题的步骤**

**Additional information/额外信息**
Please paste the information copied from the app below if you experienced a crash.
如果您遭遇了崩溃，请将从应用中复制的信息粘贴在下面。

**Comment by frg2089** [comment]
?

**Comment by frg2089** [comment]
不过审的啊

**Comment by tobiichiamane** [comment]
MS商店的审核人员是外包的，他们的审核策略是：好看的皮囊扫黄打非，有趣的灵魂应用违规
