### ISSUE TITLE
在挂了v2ray能连上墙外的情况下无法登录，一直显示登陆错误。只有开启直连才能登陆，而登陆后不显示任何内容。

### ISSUE THREAD

**Issue by larmicxx** [tobiichiamane/pixivfs-uwp#114]
General:
OS version: build 18363
App version: 2.7.4 X64
Package ID: 18416PixeezPlusProject.PixivUWP

**Comment by tobiichiamane** [comment]
如果您不采用App提供的直连，请参考https://github.com/tobiichiamane/pixivfs-uwp/blob/master/TroubleShoot.md解除本地回环

**Comment by frg2089** [comment]
https://github.com/tobiichiamane/pixivfs-uwp/blob/master/TroubleShoot.md
