### ISSUE TITLE
是不是可以添加免费热门搜索？

### ISSUE THREAD

**Issue by Sagimune** [tobiichiamane/pixivfs-uwp#25]
参考
[Pixivic](http://pixivic.com)

**Comment by tobiichiamane** [comment]
这需要我自己购买并维护数个服务器。鉴于此工程仅为业余项目，且我不打算以任何方式从中获利，我认为这是无意义的。

**Comment by Sagimune** [comment]
原来如此

**Comment by tobiichiamane** [comment]
并且，目前的开发重点是实现图片的缓存机制与瀑布流面板的虚拟化，防止浪费过多的网络资源和撑爆RAM
