### ISSUE TITLE
请求把min ver降到15063以支持mobile and请求加入黑暗模式

### ISSUE THREAD

**Issue by yuezhengbaizhi** [tobiichiamane/pixivfs-uwp#37]

**Comment by tobiichiamane** [comment]
https://github.com/tobiichiamane/pixivfs-uwp/blob/10be5515d4217b49e5d3ef03bf7733cf3025feb7/PixivFSUWP/MainPage.xaml#L29
此处使用的NavigationView不在15063版本中被支持，故无法降级最低需求版本；鉴于大部分Pixiv作品是亮色的，即使应用本身才用黑色主题，也无济于事，故并未计划黑色主题的支持。
