### ISSUE TITLE
动态磁贴和多线程瀑布流被砍了？

### ISSUE THREAD

**Issue by ZeroSimple** [tobiichiamane/pixivfs-uwp#4]
另外能不能在GitHub上发一个不限制r18的版本？

**Comment by tobiichiamane** [comment]
我相当于从头把整个应用写了一遍，很多东西还没加，这个瀑布流啊，要是同步加载所有可以加载的，会炸RAM，而且效果并不好。我打算过段时间把它改成那种看到哪儿加载到哪儿的模式。

**Comment by tobiichiamane** [comment]
> 另外能不能在GitHub上发一个不限制r18的版本？

这个不是不行

**Comment by ZeroSimple** [comment]
> 我相当于从头把整个应用写了一遍，很多东西还没加，这个瀑布流啊，要是同步加载所有可以加载的，会炸RAM，而且效果并不好。我打算过段时间把它改成那种看到哪儿加载到哪儿的模式。

加油，感谢了

**Comment by tobiichiamane** [comment]
动态磁贴看样子将被微软丢弃，暂时不作考虑

**Comment by ZeroSimple** [comment]
> 动态磁贴看样子将被微软丢弃，暂时不作考虑

微软的砍刀太可怕了……
