### ISSUE TITLE
无意中发现的，就是打开关闭操作

### ISSUE THREAD

**Issue by gegalomanic** [tobiichiamane/pixivfs-uwp#52]
**Describe the bug/描述你遇到的问题**

**How to reproduce/复现问题的步骤**

**Additional information/额外信息**
Please paste the information copied from the app below if you experienced a crash.
如果您遭遇了崩溃，请将从应用中复制的信息粘贴在下面。

**Comment by tobiichiamane** [comment]
此Issue未提供任何有意义的信息。
