### ISSUE TITLE
解除 UWP 应用本地回环限制的命令

### ISSUE THREAD

**Issue by panyuhang93** [tobiichiamane/pixivfs-uwp#55]
**Describe the bug/描述你遇到的问题**

解除 UWP 应用本地回环限制的命令文档里是
若您的应用来自于商店：
checknetisolation loopbackexempt -a -n=18416PixeezPlusProject.PixivUWP_fsr1r9g7nfjfw
我这里一直是参数错误，用了 
CheckNetIsolation.exe loopbackexempt -a -p=S-1-15-2-2869194218-4207997178-1986798348-2956709495-1396948103-3288076833-1758672343
成功了
不知道是不是大小写问题，我这里注册表的
Monker 显示的是 18416pixeezplusproject.pixivuwp_fsr1r9g7nfjfw
还是要用CheckNetIsolation.exe的问题
**How to reproduce/复现问题的步骤**

surface pro 6 安装就是这样子

**Additional information/额外信息**
Please paste the information copied from the app below if you experienced a crash.
如果您遭遇了崩溃，请将从应用中复制的信息粘贴在下面。

**Comment by panyuhang93** [comment]
不知道是不是大小写问题，我这里注册表的
Monker显示的是18416pixeezplusproject.pixivuwp_fsr1r9g7nfjfw

**Comment by tobiichiamane** [comment]
请确保您使用的cmd或者PowerShell是管理员权限的。我会在文档中加入这一项。
