### ISSUE TITLE
推荐界面下的问题

### ISSUE THREAD

**Issue by IveanEx** [tobiichiamane/pixivfs-uwp#56]
在推荐界面下，进入一张图片后再返回，页面会从顶端开始，而不是记忆上次的浏览位置。虽然问题并不大，但是修复后可以增强体验hhhh

**Comment by frg2089** [comment]
您说的返回是后退按钮还是选项卡按钮？

**Comment by IveanEx** [comment]
左上角Pixiv图标旁的返回<-按钮。我的系统版本是19041.1

**Comment by frg2089** [comment]
这个我记得开发者说做不了来着...

**Comment by IveanEx** [comment]
诶是这样的吗😂如果实在没有办法解决也没有办法啦(´⊙ω⊙`)！

**Comment by tobiichiamane** [comment]
> 这个我记得开发者说做不了来着...

不是做不了，是做起来有点麻烦，所以我懒得做了
