### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by Zhonjc2** [tobiichiamane/pixivfs-uwp#65]
一开始是可以打开的，登陆账号后闪退，然后再也打不开了，重新安装也不行，版本是Windows 10 19569

**Comment by tobiichiamane** [comment]
登录完成后立即闪退嘛，，好吧，现在的反馈机制没办法收集这种情况下的信息。待我改一改这个反馈机制、更新应用，再麻烦您测试一下。

**Comment by tobiichiamane** [comment]
请卸载当前的版本，下载[最新的测试包](https://github.com/tobiichiamane/pixivfs-uwp/releases/download/v2.6.3-b/Package.zip)，完全解压后，使用PowerShell运行其包含的install.ps1脚本文件，按照提示完成软件包部署。此版将在登录页面的左下角存在一个小按钮，在应用登录完成之前点击它，将会展示收集的崩溃信息。请将这些信息贴在这个issue下面。

**Comment by Zhonjc2** [comment]
感谢答复。重新安装以后和之前一样无法进入登陆界面，只有白色背景的Pixiv一直不动

**Comment by Zhonjc2** [comment]
等了好长时间莫名其妙的开了，然后这是信息：
General:
OS version: build 19569
App version: 2.6.3 X64
Package ID: 31db69de-89d1-4fa9-9878-fcd942f090ca
这次登陆成功了，也不知道早上是怎么回事，实在抱歉！
