### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by CFRFREE** [tobiichiamane/pixivfs-uwp#66]
**Describe the bug/描述你遇到的问题**

**How to reproduce/复现问题的步骤**

**Additional information/额外信息**
Please paste the information copied from the app below if you experienced a crash.
如果您遭遇了崩溃，请将从应用中复制的信息粘贴在下面。
General:
OS version: build 18362
App version: 2.6.1 X64
Package ID: 18416PixeezPlusProject.PixivUWP

**Comment by tobiichiamane** [comment]
This issue is meaningless.
