### ISSUE TITLE
[Feature Request] 图片遮罩修改

### ISSUE THREAD

**Issue by SettingDust** [tobiichiamane/pixivfs-uwp#67]
![image](https://user-images.githubusercontent.com/19922286/76280307-61177880-62cc-11ea-92ce-96214cac2a93.png)
![image](https://user-images.githubusercontent.com/19922286/76280352-8906dc00-62cc-11ea-87e2-31fd004497d5.png)
如图，列表中图片下部有白色半透明遮罩，当图片较长便会极大影响观感。且本身半透明遮罩便不美观。
建议将遮罩替换为下部至中部黑色渐变，字色改为白色。
作品名和和作者名间距可下调 2 左右
颜色 64%  #000 -> 0% #000 位置及方向为 100% -> 25%

原图
![custom – 1](https://user-images.githubusercontent.com/19922286/76282406-84ddbd00-62d2-11ea-9770-6d4205e0f9f4.png)

PS 处理大小
![custom – 1@2x](https://user-images.githubusercontent.com/19922286/76282132-cae65100-62d1-11ea-8fcc-f016adfe9728.png)

**Comment by tobiichiamane** [comment]
经反复测试，此种遮罩在浅色图片上将使文字难以辨识。因此暂时不作出更改。如有更好的方案，欢迎重新开启此Issue。
