### ISSUE TITLE
在图片浏览和作者个人页面中 已关注和未关注是相反的

### ISSUE THREAD

**Issue by Funny-ppt** [tobiichiamane/pixivfs-uwp#7]
在点开某图片后作者关注处显示已关注实际上是没有关注的，
显示未关注是已经关注了的，虽然作者个人页那边关注显示是正确的
等会有机会的话看下源码并PULL修正

**Comment by Funny-ppt** [comment]
看了下commit历史 看来以前是都有问题

**Comment by tobiichiamane** [comment]
2515fe93bad3b705c0e3dae927ff003a22305ef8

**Comment by tobiichiamane** [comment]
因为我目前不方便发新版本更新，所以商店里的版本还是错的

**Comment by Funny-ppt** [comment]
> 2515fe9

作品页还是有问题啊所以我才说的...

**Comment by tobiichiamane** [comment]
商店里还没有更新，，

**Comment by Funny-ppt** [comment]
> 因为我目前不方便发新版本更新，所以商店里的版本还是错的

好吧。我这边本机winsdk和项目不一样页编不过 以为还没修复

**Comment by tobiichiamane** [comment]
@all-contributors please add @Funny-ppt for bug
