### ISSUE TITLE
功能建议：1.详情页面显示标签.  2.键盘（或者鼠标拖动）控制页面滚动

### ISSUE THREAD

**Issue by yeezylife** [tobiichiamane/pixivfs-uwp#71]
1.pixiv网页上每个图片下方会有很多标签，这样点标签可以浏览类似的图片，同时也能防止自己觉醒了某些奇怪的趣♂味。
2.好像只能鼠标滚轮控制上下滑动？  加上键盘控制或者滚动条是不是更好操作呢。

**Comment by yeezylife** [comment]
我擦 默认就是bug啊 我想改enhancement。。

**Comment by tobiichiamane** [comment]
标签我本来想加上的，但是每次都在加上之前忘掉了，所以一直没有加。不加滚动条是为了避免奇怪的UI问题。

**Comment by yeezylife** [comment]
> 标签我本来想加上的，但是每次都在加上之前忘掉了，所以一直没有加。不加滚动条是为了避免奇怪的UI问题。

我想标签还是挺需要的，能帮助自己更能了解图片内容，另外官网的标签还自带翻译，不用担心看不懂。     第二个问题的话。。键盘方向键控制上下可行么。。

**Comment by yeezylife** [comment]
@tobiichiamane   还。。还有。。。  每次返回“推荐”页面的时候， 页面会自动回到最顶部，每次都得重新往下刷。。
