### ISSUE TITLE
点开图片一直显示“正在创建时间线”（已经破解本地回环了，挂ssr也没用）

### ISSUE THREAD

**Issue by Ayanami-hqy** [tobiichiamane/pixivfs-uwp#77]
#**Describe the bug/描述你遇到的问题**

**How to reproduce/复现问题的步骤**

**Additional information/额外信息**
Please paste the information copied from the app below if you experienced a crash.
如果您遭遇了崩溃，请将从应用中复制的信息粘贴在下面。

**Comment by tobiichiamane** [comment]
请启动应用程序，点击右上角最左边的反馈按钮，将信息贴在此issue内。
