### ISSUE TITLE
无法加载详情大图（一直显示正在创建时间线）

### ISSUE THREAD

**Issue by Ayanami-hqy** [tobiichiamane/pixivfs-uwp#80]
**Describe the bug/描述你遇到的问题**

**How to reproduce/复现问题的步骤**

**Additional information/额外信息**
Please paste the information copied from the app below if you experienced a crash.
如果您遭遇了崩溃，请将从应用中复制的信息粘贴在下面。

General:
OS version: build 18362
App version: 2.6.5 X64
Package ID: 18416PixeezPlusProject.PixivUWP

![image](https://user-images.githubusercontent.com/62933729/79064922-57c06800-7cdf-11ea-9042-10f8bc097c1c.png)

**Comment by frg2089** [comment]
?

**Comment by Ayanami-hqy** [comment]
> ？

不管是直连还是挂ssr都不行

**Comment by frg2089** [comment]
- [本地回环](https://github.com/tobiichiamane/pixivfs-uwp/blob/master/TroubleShoot.md), 请检查是否解除Pixiv UWP应用的本地回环限制
- 网络问题, 请检查网络连接
- 请求超时, 请稍后重试

**Comment by Ayanami-hqy** [comment]
> * [本地回环](https://github.com/tobiichiamane/pixivfs-uwp/blob/master/TroubleShoot.md)，请检查是否解除Pixiv UWP应用的本地回环限制
> * 网络问题，请检查网络连接
> * 请求超时，请稍后重试

本地回环已解除；
挂ssr、直连可正常看缩略图、收藏；
自2月下载以来一直存在这个问题，重试无数遍了

**Comment by Ayanami-hqy** [comment]
> * [本地回环](https://github.com/tobiichiamane/pixivfs-uwp/blob/master/TroubleShoot.md)，请检查是否解除Pixiv UWP应用的本地回环限制
> * 网络问题，请检查网络连接
> * 请求超时，请稍后重试

![image](https://user-images.githubusercontent.com/62933729/79065681-cd7b0280-7ce4-11ea-95d8-cf3a8d71f713.png)
![image](https://user-images.githubusercontent.com/62933729/79065700-edaac180-7ce4-11ea-9723-a90232c3d703.png)

**Comment by Ayanami-hqy** [comment]
> * [本地回环](https://github.com/tobiichiamane/pixivfs-uwp/blob/master/TroubleShoot.md), 请检查是否解除Pixiv UWP应用的本地回环限制
> * 网络问题, 请检查网络连接
> * 请求超时, 请稍后重试

![image](https://user-images.githubusercontent.com/62933729/79065757-3febe280-7ce5-11ea-85f7-dcd0d4892e16.png)
随便选一个点开，都是一直保持这个界面（下载啥的都可以秒下）

**Comment by frg2089** [comment]
哦吼...等主要开发者来吧...

**Comment by tobiichiamane** [comment]
@Ayanami-hqy 无法复现你的问题。请在遭遇该情况后立即点击应用右上方，您头像左侧的反馈按钮，并将收集到的信息粘贴在此Issue内。

**Comment by Ayanami-hqy** [comment]
> @Ayanami-hqy 无法复现你的问题。请在遭遇该情况后立即点击应用右上方，您头像左侧的反馈按钮，并将收集到的信息粘贴在此Issue内。

General:
OS version: build 18362
App version: 2.6.5 X64
Package ID: 18416PixeezPlusProject.PixivUWP

**Comment by Ayanami-hqy** [comment]
![image](https://user-images.githubusercontent.com/62933729/79125557-f8db1b80-7dd0-11ea-89f9-9651b80bdce0.png)
![image](https://user-images.githubusercontent.com/62933729/79125610-05f80a80-7dd1-11ea-97d3-4dff513c17a1.png)

还是这个亚子啊

**Comment by tobiichiamane** [comment]
没有记录到任何异常。考虑网络质量问题

**Comment by Ayanami-hqy** [comment]
> 没有记录到任何异常。考虑网络质量问题

所以有什么可能的解决办法吗

**Comment by tobiichiamane** [comment]
暂时没有。我会调查这个问题的

**Comment by Ayanami-hqy** [comment]
> 暂时没有。我会调查这个问题的

还是谢谢了

**Comment by Ayanami-hqy** [comment]
重装系统，问题解决了

**Comment by tobiichiamane** [comment]
嗯，看来是系统处理时间线有点问题
