### ISSUE TITLE
文字显示不全

### ISSUE THREAD

**Issue by rainyuxuan** [tobiichiamane/pixivfs-uwp#85]
部分文字（"unmarked", "unfollow"）显示不完整
![image](https://user-images.githubusercontent.com/42298884/82110459-c0e73100-970c-11ea-9eb1-8bff4680d760.png)

**Comment by tobiichiamane** [comment]
已知的问题，但是没有有效的解决方案，除非重新设计UI

**Comment by tobiichiamane** [comment]
42dc0ec873da4a17546713dc701c592c68c937fe
