### ISSUE TITLE
“返回”按钮逻辑优化

### ISSUE THREAD

**Issue by Ayanami-hqy** [tobiichiamane/pixivfs-uwp#87]
### 按钮逻辑优化
![TIM截图20200524170416](https://user-images.githubusercontent.com/62933729/82750240-4770d200-9de1-11ea-82cc-182bffe63cd6.png)
![TIM截图20200524170507](https://user-images.githubusercontent.com/62933729/82750241-4b045900-9de1-11ea-9b0c-5652014fddf4.png)
 ![TIM截图20200524170541](https://user-images.githubusercontent.com/62933729/82750244-4f307680-9de1-11ea-977c-ebf384776071.png)
如同，打开画师主页后再点击“作品”，选一张插画打开后再点返回会回到画师主页
希望点返回的时候能回到画师作品页面，而不是画师主页

**Comment by YukinoShary** [comment]
#88 包括搜索结果页的返回逻辑与作者主页的返回逻辑都已经修改了
