### ISSUE TITLE
允许本地回环之后仍然无法登录建议添加Sockes5

### ISSUE THREAD

**Issue by Castleeee** [tobiichiamane/pixivfs-uwp#9]
谢谢作者，软件很好用

**Comment by tobiichiamane** [comment]
请确保您真的允许了本地回环，并且代理工具可以正常代理如下的域名：
- app-api.pixiv.net/*
- public-api.secure.pixiv.net/*
- oauth.secure.pixiv.net/*
- public-api.pixiv.net/*

为保证图片加载速度，您还需要代理如下域名：
- i.pximg.net/*

**Comment by tobiichiamane** [comment]
哦，Pixiv的登录API作了修改，请耐心等待我完成对应的修改

**Comment by Castleeee** [comment]
谢谢👌

**Comment by tobiichiamane** [comment]
问题已经得到解决。见位于[pixivcs仓库](https://github.com/tobiichiamane/pixivcs)的[此提交](https://github.com/tobiichiamane/pixivcs/commit/da674f2454e36d93bfff3934d4bcf2c8b394977a)和本仓库的[此提交](https://github.com/tobiichiamane/pixivfs-uwp/commit/c83d16733d4376593124507b631dd5877bbac41d)。版本[v2.2.2](https://github.com/tobiichiamane/pixivfs-uwp/tree/v2.2.2)解决了该问题，您可以从[releases页面](https://github.com/tobiichiamane/pixivfs-uwp/releases/tag/v2.2.2)获取该版本的软件包，或等待应用商店更新。
